services:
  app:
    container_name: scan-code-qr
    image: golang:1.23-alpine
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "GOOS=linux GOARCH=amd64 go build -o app && ./app"
    networks:
      - main-external-network
      - scancode-qr-external-network
networks:
  main-external-network:
    external: true
  scancode-qr-external-network:
    external: true
